---
title: "REAL McCOIL Data"
author: "Aris Paschalidis"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    highlight: pygments
    toc: true
    toc_float: true
    number_sections: true
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
# Here, we set default options for our markdown file
knitr::opts_chunk$set(
  comment = "#>",
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 80)
)
# Change the way tibble prints so only prints 5 extra columns
options(tibble.max_extra_cols = 5)

# Function to determine if pbapply is installed. If it is installed, it will
# display a progress bar
list_apply <- function(x, fun, ...){
  if (requireNamespace("pbapply", quietly = TRUE)) {
    pbapply::pblapply(x, fun, ...)
    } else {
    lapply(x, fun, ...)
  }
}

library(coiaf)
```

# Run Real Data

In this analysis file, we run our COI algorithm on a collection of real data.

```{r read data}
# Path to data
path = "~/Desktop/Malaria/COI data/"

# Read in the real data and the REAL McCOIL COI predictions
rmcl_wsafs   <- readRDS(paste0(path, "RMCL_wsafs_unique.rds"))
rmcl_coi_out <- readRDS(paste0(path, "RMCL_coi_out.rds")) %>% 
  tibble::as_tibble() %>% 
  dplyr::mutate(dplyr::across(c(file, name), as.character)) %>% 
  dplyr::rename(rmcl = COI) %>% 
  dplyr::rename(rmcl_025 = COI_025) %>% 
  dplyr::rename(rmcl_975 = COI_975)
```

Run our data, set it up in an ideal format and save the data sets as .rds files

```{r run data}
raw_predictions <- list_apply(seq_len(length(rmcl_wsafs)), function(x) {
  # Run predictions
  sample <- rmcl_wsafs[[x]]
  predicted <- run_real_data(sample)

  # Extract coi from the predictions
  extract_coi <- tibble::enframe(unlist(lapply(predicted, function(x){ x$coi })),
                                 value = "prediction") %>%
    dplyr::mutate(file = names(rmcl_wsafs)[x])

  # Summarize over the 5 rmcl runs
  rmcl_outputs <- rmcl_coi_out %>%
    dplyr::filter(stringr::str_detect(file, names(rmcl_wsafs)[x])) %>%
    dplyr::group_by(name) %>%
    dplyr::summarise(rmcl = mean(rmcl),
                     rmcl_median = median(rmcl),
                     rmcl_025 = mean(rmcl_025),
                     rmcl_975 = mean(rmcl_975),
                     .groups = "drop")

  # Join the tibbles and find difference
  res <- dplyr::full_join(extract_coi, rmcl_outputs, by = "name")
  return(res)
})
names(raw_predictions) <- names(rmcl_wsafs)

# Set up a tibble with all the information from the runs
complete_predictions <- raw_predictions %>%
  dplyr::bind_rows() %>% 
  dplyr::mutate(difference_mean = prediction - rmcl) %>% 
  dplyr::mutate(difference_median = prediction - rmcl_median) %>%
  dplyr::mutate(in_CI = ifelse(prediction >= rmcl_025 & 
                                 prediction <= rmcl_975, 1, 0)) %>%
  dplyr::mutate(Region = as.numeric(stringr::str_extract(file, "(?<=region_)[:digit:]*"))) %>% 
  dplyr::mutate(VCF = as.numeric(stringr::str_extract(file, "(?<=vcf_)[:digit:]*"))) %>% 
  dplyr::relocate(file, .after = tidyselect::last_col())

# Save data
saveRDS(raw_predictions, file = "analysis/rmcl_raw_predictions.rds")
saveRDS(complete_predictions, file = "analysis/rmcl_complete_predictions.rds")
```

Plot the results looking at COI and comparison to REAL McCOIL.

```{r plots}
ggplot(complete_predictions, aes(factor(prediction), 
                                 fill = factor(prediction))) +
  geom_bar(stat = "count") + 
  facet_wrap(. ~ Region, nrow = 4, scales = "free", labeller = "label_both") + 
  ggsci::scale_fill_d3() +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5, size = 13),
        axis.title = element_text(size = 10)) +
  guides(fill = FALSE) +
  labs(x = "Predicted COI", y = "Count", title = "Predicted COI in Each Region")

ggplot(na.omit(complete_predictions), aes(factor(difference_median), 
                                          fill = factor(difference_median))) +
  geom_bar(stat = "count") + 
  facet_wrap(. ~ Region, nrow = 4, scales = "free", labeller = "label_both") + 
  # ggsci::scale_fill_d3() +
  theme_classic() +
  theme(plot.title  = element_text(hjust = 0.5, size = 13),
        axis.title = element_text(size = 10)) +
  guides(fill = FALSE) +
  labs(x = "Difference Between coiaf And REAL McCOIL Median", y = "Count", 
       title = "Difference Between coiaf And REAL McCOIL Median By Region")
```

# World Maps

World map with average COI

```{r world map}
## What would be ideal is to somehow find the lat and long of each patient
## then, it would be a lot simpler to plot these types of graphs
world <- ggplot2::map_data("world")
average_coi <- complete %>% 
  dplyr::group_by(Region) %>% 
  dplyr::summarise(coi_mean = mean(prediction),
                   coi_med = median(prediction), .groups = "drop")

# Meta come from the 03 analysis file!
# In order to get the 24 regions, I take the mean of the lat and long of all
# the patients in each region. This is not the best way to do this, but it is
# the simplest way.
test <- meta %>% 
  dplyr::group_by(color) %>% 
  dplyr::summarise(lat = mean(Lat),
                   long = mean(Long), .groups = "drop")
test$color <- as.numeric(test$color)

# Combine lat and long with the average coi from our predictions
map_data <- dplyr::full_join(average_coi, test, by = c("Region" = "color"))

ggplot() +
  borders("world") +
  geom_polygon(data=world, aes(x=long, y = lat, group = group), fill="grey", alpha=0.3) +
  geom_point(data=map_data, aes(x=long, y=lat, size=coi_med, color=coi_med)) +
  scale_color_viridis(limits = c(1, 2), breaks = c(1.0, 1.5, 2.0)) + 
  theme_void() + 
  theme(legend.position = "bottom") +
  scale_size(guide = "none") + 
  labs(color = "Median COI") +
  coord_quickmap(xlim = c(-75, 150), ylim = c(-20, 20))
```

World map with all data

```{r all patients map}
tf <- tempfile()
download.file("ftp://ngs.sanger.ac.uk/production/malaria/pfcommunityproject/Pf6/Pf_6_samples.txt",tf)
meta <- data.table::fread(tf)

world <- ggplot2::map_data("world")
patient_lat_long <- dplyr::left_join(complete, meta, by = c("name" = "Sample")) %>% 
  dplyr::filter(prediction <= 10) %>% 
  dplyr::arrange(desc(prediction))

ggplot() +
  borders("world") +
  geom_polygon(data=world, aes(x=long, y = lat, group = group), fill="grey", alpha=0.3) +
  geom_point(data=patient_lat_long, 
             aes(x=Long, y=Lat, size=prediction, color=prediction), alpha=0.1) +
  scale_color_viridis(limits = c(1, 10)) +
  theme_void() + 
  theme(legend.position = "bottom") +
  scale_size(guide = "none") + 
  labs(color = "COI") +
  coord_quickmap(xlim = c(-75, 150), ylim = c(-25, 25))
```

